---
baseurl:                    https://tenchi.team2xh.net/
languageCode:               en
title:                      COMMENT BLOCKS

theme:                      commentblocks
pygmentsStyle:              monokai
pygmentsUseClasses:         false
pygmentsCodeFences:         true
pygmentsOptions:            linenos=table

metaDataFormat:             yaml
googleAnalytics:            UA-19987743-3
disqusShortname:            commentblocks
publishdir:                 dist

params:
    name: Hamza Haiken
    description: Posts about my free time projects
    bio: /* COMMENT BLOCKS */
    twitter: 2xhTenchi
    enableRSS: false

    home: HOME
    about: ABOUT
    subscribe: 
    olderPosts: OLDER
    newerPosts: NEWER
    readMore: READ MORE
    copyright: 

    aboutAuthor: Enthusiastic hacker
    tweet: 
    share: 

    title404: 
    subtitle404: 

    socialIconStyle: rounded
...